language: scala

jdk:
  - oraclejdk8

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m ";^test:compile"
  - git diff --exit-code --color || { echo "[error] Unformatted code found. Please run 'test:compile' and commit the reformatted code."; false; } && sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ";test"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

deploy:
  provider: script
  script:
    - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ^publish
  on:
    tags: true
    repo: akka/akka-paradox

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "TZ5/EpN2ZlMaEoY3A/tSkhia6pJm8dAOs5Be2uE7GVl9O/frE8fgp96G8kI6PicexM5Awwpkf94o50FVWx+89GyXVDHMPlOUIdiPANPo7YlNjgovzVAF5i6HK5nqpJWetdp+i/JanMDCJ9Cu9A+vE6KTUat1ye0qKLW2s8TOWMpL9Zz/fq1eQmZNvXOzBwMVYfDLXILYYOw5AdeS8o2OYw+rpymTU5oHwT0xOAdTAYSUqKJGPeWzg7wI/npZmCJ7h/JS3rZxdEWmWSRg+6zIOOtHm5ggPB4/TkoT9me/OobYex53tmeowRBFGVojfPK0UGvqJtMuMkv+GMu9oqBiVrf+XNMwDc8Awe0ewv9CRfTY4GnqLicePFS83Xo9KT1PqxzeEAO+kbL40gIZgoySvlwrgfGBvXRm4ucAjDB2ZBa6wGEJwWDYISH7yXJ2NVSlGQ1DpepwwuDfrKCuwbZLbK1wpS/KkOW4vFlHkYbiPmwmTtnxpb0zhzzCCemb9yDn395IDHCRzGolY3Q9ic6JQlxKXPBDkzwG/Qb27y5XdQ0WKow+9EvWGzbHFnsAzR7XtKL2oOUWLpD4G1D7/nP/zwAXifrN2O5aoM0wjXWDBAtaOXhd2D3xy9uS3zC0r2v9Ht43L+Syb962Dc0MvGHe0rfXi08TafsQEi+xiK2xC8o="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    # and use your API key
    - secure: "nFT49vgJlYAGYlrGlmIC4WDoFuu9brTCdzds4afHuBxnKTeu3omrA0Tprw81mDWe9ZJ31csVvE4OxuUq5VhSrYGV3qCSRiAMuElQOyx2I4Bk9DcLDBTGbagzvV0cQJwVjiKMgWNsV4R49AgSqSgerFet2iRvG4YKuikF95sg1SQtBYjtvmp4ByU9iOiAGJj/AVil67cOErDfjoJisV/1VZhRt51RFO3li8l23kjqGqfxsKLHgXLh+RVmKylud2FrD/cTuYGJdAwOVvGiJOXX2vZ1gxWYj1pP1+YKIQfZCUQukpKJrjuxzBP8jBElA/0dlMZkfL+H3lUFlvYToDK43YlW5cQI6Yuz29aeZjGZsx41KYPP9TFLrxKzSnHi6tm1jwpl6M0KqWvGpozUfKyI5LgzOmiVXKG8KhY2aVotFxkaeY5vxyaU2ccl56/5VFAEiutZYKtVM9tBNTmwvzORlAj7ALZ7EA/Ih3yE7S58v4ISs7zS8nxNXcT7FVlh4huMFJTPMKByn81i5rsd9BaUS1WOhHPE1tHnupgtAbFBhHBUW0ocUIQcdQUvu1H/Ai/eN06ekQAdq6RWypaZtqrZ+V3G5Eny87DwUt0EqN4VfW1RZOaSzdZboRaKM1hlJS44wLGzR7IEWyPG+heECelZondrIc3RUE4iM5QbQIZo4WU="
